version: 2.1

jobs:
  build:
    docker:
      - image: 'node:alpine'
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Start creating an image with Dockerfile.dev
          command: docker build -t react -f Dockerfile.dev .
      - run:
          name: Run tests
          command: docker run react npm test -- --coverage
      - run:
          name: Test success
          command: echo "Test success"

workflows:
  version: 2
  build-workflow:
    jobs:
      - build